name: BlocksTop
author: DerRedstoner
version: 1.1
main: de.derredstoner.blockstop.BlocksTop

commands:
  blockstop:
    aliases: [bt]

permissions:
  bt.top:
    default: true
  bt.force:
    default: op
  bt.reload:
    default: op